### PR TITLE
Upgraded to Google Billing v6.0

### PR DESCRIPTION
**Pull request by mert-karadeniz**
* Upgraded to Google Billing v6.0
* The access issue with the parameters 'oneTimePurchaseOfferFormattedPrice' and 'subscriptionOfferDetails' has been resolved.

### CODE REVIEW

**Comment by mert-karadeniz** [comment]
Hi Moisoni.

I haven't been able to focus on the library for quite some time due to a heavy workload. Now, Google is making it mandatory for us to use version 5.0 or higher for the library. Honestly, I hadn't tested the v5.0 library in my own project before. However, I recently decided to upgrade the version we have in production and address any issues that might come up. I ran tests in my own project and didn't encounter any problems so far. Currently, I have full access to all the parameters. I would appreciate it if you could also take a look and provide your feedback. Thank you!

**Comment by moisoni97** [comment]
Thanks again for taking the time to upgrade the library!
We appreciate!

**Comment by mert-karadeniz** [comment]
Hi @moisoni97 

When can you share the project on Jitpack?

**Comment by moisoni97** [comment]
Done, @mert-karadeniz !

**Comment by mert-karadeniz** [comment]
Thank you!

**Pull request merged**
